<?php

use Symfony\Component\HttpFoundation\RedirectResponse;


function countlikes_theme($existing, $type, $theme, $path) {
//  \Drupal::service('page_cache_kill_switch')->trigger();
return [
  'diadia' => [
    'variables'=> [
     //'creado1' => NULL,

   ],
 ],
];
}

/*function newsletter_sularyy_mail($key, &$message, $params) {

  $body =
"Hola,

Demano Informació de les cistelles de la Rural

mi correu: " . $params['email'] . "

Merci";

  $message['subject'] = "Informació cistellas";
  $message['body'][] = Drupal\Core\Mail\MailFormatHelper::htmlToText($body);
}*/
